### ISSUE TITLE
Autosave system performance improvement

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#103]
**Is your feature request related to a problem? Please describe.**
Autosave is a very useful feature, but many users wish to disable it due to it being too slow and causing too much lag while the project is open.

**Describe the solution you'd like**
The autosave system needs to be optimized for faster performance.

The main issue is that the entire project must be serialized then saved in localstorage. If only the parts of the project that changed could be processed, then the autosave routine would only have to handle a tiny portion of the project at any time.

**Comment by Luxapodular** [comment]
the new autosave system is currently under development: see commit a54d174a91cd400a96c6425f0089761aafb208ff of new-autosave branch.

Next Steps: 
- Plug in assets
- Test with larger projects
- Fix ObjectCache issues (see #123 )

**Comment by Luxapodular** [comment]
Autosave is now currently working and plugged in on the fix-autosave branch. Last steps to this are:

- Add delete autosave functionality + tests
- Adding additional integration tests, and some manual tests with larger projects.
