### ISSUE TITLE
Add scaleX and scaleY to the inspector

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#105]
**Is your feature request related to a problem? Please describe.**
Currently, only the width and height of objects can be changed through the inspector. The user is completely responsible for calculating the scale value if they want to scale for example, 2x (if the object is 100 pixels, then you must change the width to 200px - it would be easier to just change scaleX to 2).

**Comment by Luxapodular** [comment]
scaleX and scaleY were added to selection and the inspector in the scale-selection branch commit 848002321b41ee3ea1f4bb4e251a38aded13f222 along with tests!
