### ISSUE TITLE
Red/blue onion skin tint option for objects before/after the playhead

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#109]
**Is your feature request related to a problem? Please describe.**
Some animators find it useful for there to be a color tint on onion skinned objects.

**Describe the solution you'd like**
An option to enable a red+blue, green+yellow, etc. color tint to objects before+after the playhead position, respectively.

**Additional context**
An example of what this feature should look like:
![onionskinning2](https://user-images.githubusercontent.com/4970417/71915071-f66d8380-3148-11ea-88ec-6464ed8236e6.png)

**Comment by zrispo** [comment]
Current progress on this - we have colored outlines working!

![Screen Shot 2020-01-28 at 3 52 36 PM](https://user-images.githubusercontent.com/4970417/73304452-45598680-41e6-11ea-88fc-f7061ba7e5af.png)

**Comment by Luxapodular** [comment]
I'm currently integrating these settings into the "project settings" modal, under a new "Editor Settings" tab. A byproduct is that now tool settings are being saved between sessions!

**Comment by Luxapodular** [comment]
The "outline" system is almost working in all cases.

There are two bugs that need to be addressed prior to integrating this into 1.17 . 

1) When adding tweens to frames that are onion skinned, the re-colored objects will be saved.

2) Objects that are not paths are not outlined/recolored properly.

Below is a bug showing both issues.

![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/8699557/78047120-fcd55b00-7345-11ea-8f74-f3533828ba1e.gif)
