### ISSUE TITLE
Paths, Clips, and Clips with code should be visually different on the canvas

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#111]
**Is your feature request related to a problem? Please describe.**
It's difficult to tell which objects on the canvas are Paths or Clips without selecting them and looking in the inspector. It is also difficult to tell which objects have code on them.

**Describe the solution you'd like**
Some visual differences between these objects is needed, such as a different color border, a "has code" icon, etc.
Hovering over paths/rasters/text could also render overlays over them (blue strokes, image pattern fill).

**Comment by Luxapodular** [comment]
Accidentally closed this issue.

**Comment by Luxapodular** [comment]
![image](https://user-images.githubusercontent.com/8699557/72624219-8fa05500-3914-11ea-8cf3-b3d2d5a05cb3.png)

Images from our design brainstorm this morning
