### ISSUE TITLE
Sound Improvements

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#112]
**Is your feature request related to a problem? Please describe.**
The sound system/API is missing a few key features.

**Describe the solution you'd like**
- (done) An API method to stop a specific sound (as opposed to `stopAllSounds`)
- (done) Volume control in inspector
- (done) Volume control in params in `playSound`
- <s>"Stream" vs "Event" sounds (play whole sound or play part of sound cropped to fit the frame)</s> (Moved to separate issue #127 )
- V(done) isually change the waveform based on frame `soundVolume`

**Comment by Luxapodular** [comment]
Additional elements to consider.
- Sound volume needs to translate to video exporter.
- Soundstart needs to work in video exporter
- Sound start needs to be added to inspector

At some point, we need an interface control for soundstart, but right now it's out of scope.
