### ISSUE TITLE
Animated GIF -> Clip import

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#118]
**Is your feature request related to a problem? Please describe.**
In Legacy Wick Editor, you could import an animated GIF and Wick would convert it into a Clip with each frame of the GIF converted into a frame on the timeline of the Clip.

**Describe the solution you'd like**
Bring this feature back!!

**Comment by Luxapodular** [comment]
- gif files should have correct names in asset library
- gif files should end in .gif
- gif files should be searchable by name.gif with filter
- gif icon for gif objects

**Comment by Luxapodular** [comment]
- When deleting gifs from asset library, child images should also be deleted.
