### ISSUE TITLE
SVG Import

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#119]
**Is your feature request related to a problem? Please describe.**
In Legacy Wick Editor, SVGs could be imported into projects.

**Describe the solution you'd like**
Bring this feature back!

**Comment by olivetthered** [comment]
This is now implemented pending some design considerations before merging into the main branch.
[https://imgur.com/2XuY7VQ](url)
<img width="1834" alt="2020-03-31" src="https://user-images.githubusercontent.com/37796246/78082668-7ce1dc00-73ab-11ea-860b-1f78ca618b72.png">

**Comment by olivetthered** [comment]
there's some historical importSVG code that is a partial implementation from a past attempt at implmenting SVGImport that needs to be cleared up too.

**Comment by olivetthered** [comment]
linking the Base items that are using the SVGAsset needs to be completed
there needs to be an svg ison for the asset
and ideally imports need to be moved so that they are centered around the mouse coursor when drag/dropped from the asset box.

Those three things and this should be complete.

**Comment by olivetthered** [comment]
ClipAsset currently doesn't support getInstances &co. and it's implementation would be pretty much identical to the one SVGAsset would use. I guess, that being the case, that it's not critical to implement at the moment and a solution that fits many assets can be looked at being implemented in the future.

**Comment by olivetthered** [comment]
<img width="932" alt="correctly importing svg files with their groups as clips" src="https://user-images.githubusercontent.com/37796246/79673660-848ae880-81d3-11ea-927c-2a147cc62e8a.png">

There's currently an issue with z-orders in some svg files and scaling could be managed better but appart from that it's good to merge. my origional implementation had a bug where loading the svg file just created an inplace copy of the paper.item and didn't create the correct wick objects. I fixed the bug and it's now importing svg files into clips that can be broken appart into their elements.

**Comment by olivetthered** [comment]
zorder has been fixed
