### ISSUE TITLE
PNG Sequence Export

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#120]
**Is your feature request related to a problem? Please describe.**
It is very useful to be able to export all the frames of your project as a sequence of lossless PNGs (in case you want to edit your animation in a different program, want to render your video using a different method other than Wick's ffmpeg options, etc).

**Describe the solution you'd like**
An option to export the project as a ZIP file containing numbered PNGs.

**Comment by kryptot7** [comment]
I think both this feature and #121 would benefit from being broken down into two intuitive functions:
* Export Image (either PNG or SVG)
   - Captures the way the stage looks on screen and saves it as an image. If you have object(s) selected, the image will only include those, and it will be transparent and cropped.
* Export Image Sequence
   - Captures every frame of the root timeline and saves each as an image. If you have any Clips selected, Wick will capture them instead, saving each Clip's frames separately as a transparent image sequence. (e.g. ClipA_frame0001, ClipB_frame0001, etc.)

**Comment by Luxapodular** [comment]
@kryptot7 Definitely splitting this functionality into two distinct functions is the way to go! I'm thinking of adding an additional tab to the export menu itself for these actions.

Also, we probably want to add an option for exporting as a PNG sequence with transparent backgrounds!
