### ISSUE TITLE
[BUG] Gifs and image sequences are exporting with black bars on projects over 405px in height

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#128]
**Describe the bug**
Gifs and image sequence export are creating black bars on the bottom of the image on projects over 405 pixels in height

**To Reproduce**
1. Open a blank project
2. Set the height of the project to any value over 405.
3. Export a gif.
4. See error: a black bar will appear at the bottom of the image.

**Expected behavior**
The image should display without a black bar.

**Screenshots**
An image exported at 600x600
![My Project(2)](https://user-images.githubusercontent.com/8699557/72671366-f6a63280-3a16-11ea-93c1-39a122d48de6.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser [Firefox]
 - Version 72.0.1 (64-bit)

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**

This problem either originates within project.generateImageSequence() or the bars are actually the bars which black out the sides of projects when exported using Zip or HTML.

**Comment by Luxapodular** [comment]
Looks like this issue does not occur on my windows 10 machine. I am assuming this is some type of devicePixelRatio issue, as the Mac tested on has a retina display.

**Comment by gameyboy11** [comment]
I know this is already closed but I also have a windows 10 machine and have the same issue. I would send a picture but I don't know how.

**Comment by gameyboy11** [comment]
also for me its happening in version 1.19.4
