### ISSUE TITLE
Clips should have the option to "sync" with their parent timeline

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#134]
**Describe the solution you'd like**
In Flash/Animate, a Graphic can be used in place of a MovieClip when you want a looping animation as part of your animation, but you also want to be able to see the looping animation when you preview/scrub the main animation.

Another part of this option is the ability to have Clips stop on a specific frame. This was very useful for lip syncing (make a clip with several mouths on each frame, make multiple frames with that clip, and change the "starting frame" of the clip on each frame).

**Comment by kryptot7** [comment]
I created some mockups and proposals for this and #135 here:
https://forum.wickeditor.com/t/clip-api-ideas/1697/5
The last post is the most relevant. It might help as you implement this feature.
Thanks for working on this! 😄
