### ISSUE TITLE
[BUG] .wickobj files with images included do not import correctly

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#137]
**To Reproduce**
1. Export a .wickobj file with an image on the first frame
2. Create a new project and import that .wickobj file

The image will not appear in the new project because that project does not have the original image asset.

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**

Assets inside Clips must be included with the .wickobj format.

**Comment by Luxapodular** [comment]
This looks to have been fixed. wickobj's now store image information.
