### ISSUE TITLE
[BUG] Object identifier names cannot be reset to "" (empty string).

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#143]
**Describe the bug**
When attempting to remove a frame or object's identifier name, you cannot make the name empty string.

**Expected behavior**
Objects should allow empty names.

**Screenshots**
<img width="255" alt="Screen Shot 2020-02-02 at 12 59 46 PM" src="https://user-images.githubusercontent.com/8699557/73612691-e916ae00-45bb-11ea-90ca-c61b80bbfc62.png">

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**

This is occurring because "empty name" is not considered a valid identifier name by the engine.

**Comment by nick-wick** [comment]
String validator in WickInput didn't let you set to empty string, now it does
