### ISSUE TITLE
Dragging assets from outside editor should upload them automatically.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#148]
**Is your feature request related to a problem? Please describe.**
In Wick Editor Alpha, this feature existed. It's very useful.

**Describe the solution you'd like**
When a user drags an image, or sound, file onto the canvas or timeline, that image or sound should be automatically converted to an asset and added to the resepective part of the project.

**Comment by zrispo** [comment]
Additionally, we should render a "Drop to Upload" div when files are dragged over the editor.
