### ISSUE TITLE
[BUG] When assets are deleted from asset library, all instances of that asset should be deleted from project.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#156]
**Describe the bug**
Asset instances remain after their parent has been deleted.

**Comment by zrispo** [comment]
All assets are working now except for GIFs. When you delete a GIF asset, it should automatically delete all of the images of each GIF frame.

**Comment by olivetthered** [comment]
SVGAsset still needs instances implementing. I'll get it done over the next day or so.
