### ISSUE TITLE
[BUG] Rotation is restricted between -180 and 180 degrees.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#159]
**Describe the bug**

**To Reproduce**
Major bug with tweens:
You can't tween anything past 180 degrees, even using multiple tweens.

How to recreate:
1. create a shape, make it a tween
2. make a 2nd tween keyframe, click the shape and type 170 degrees, it moves 170° clockwise as expected
3. make a 3rd tween keyframe, type 190°. Wick changes your input to -170°. Press play and it ends up turning 340° counter-clockwise.

Why it's a major issue:
Currently it's impossible to animate anything that rotates more than 180 degress, such as wheels.

**Additional context**
A quick fix could be to allow users to rotate between -360 and 360 degrees.

**Comment by zrispo** [comment]
Current solution:

- Re-enable the `fullRotations` option in the inspector
- Disable the clamping in Tween.js (https://github.com/Wicklets/wick-editor/blob/master/engine/src/base/Tween.js#L74)

Next steps:

- Automatically update `fullRotations` based on how many degrees were lost after clamping `rotation`

**Comment by Luxapodular** [comment]
Fullrotations is now live on test, should push with 1.17
