### ISSUE TITLE
cand npm build engine on windows

### ISSUE THREAD

**Issue by olivetthered** [Wicklets/wick-editor#168]
There's currently no script to build the engine on windows using npm rub build-engine-windows

**Comment by olivetthered** [comment]
find patch in pastbin link [https://pastebin.com/5zQbxJ6W](url)

**Comment by olivetthered** [comment]
the mkdir could be removed and just xcopy create the directory if it doesn't already exist.

**Comment by kryptot7** [comment]
@olivetthered That link seems to be broken.
I made a .bat file that built the engine in my old fork kryptot7/wick-editor, but it doesn't work anymore:
https://github.com/kryptot7/wick-editor/blob/clip-and-reference-features/build-engine.bat

It worked well last summer when I wrote it, but when I updated the fork in November, it stopped functioning properly and caused errors in the editor. I wasn't sure why.

**Comment by Luxapodular** [comment]
This has been updated with the build-engine-windows command.
