### ISSUE TITLE
Built-in console logging area

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#173]
Users have to use the browser's web console to log output, which slows down the whole editor.

It would be very useful to have a small window that automatically pops up when a user uses `console.log`, or a custom Wick API call.

**Comment by ComradeSparklePony** [comment]
This appears to exist in Wick 1.19 ([test.wickeditor.com](https://test.wickeditor.com)), with `console.log`.

Is revisiting all these issues helpful? If it's just spammy I can stop.

**Comment by Luxapodular** [comment]
> Is revisiting all these issues helpful? If it's just spammy I can stop.

This is actually very useful for review, thanks!

This feature was added with the new console update in 1.19.
