### ISSUE TITLE
[BUG] The fill bucket sometimes runs incredibly slow.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#178]
**Describe the bug**
Somewhat randomly, the fill bucket takes a considerable amount of time to run.

**To Reproduce**
Needs Investigation: This issue seems to be somewhat random.

**Expected behavior**
Filling should be nearly instantaneous.

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**
The flood fill algorithm currently being used is not optimized and quite old. Another issue could be in the up scaling of the drawings during the raster step.

**Comment by nick-wick** [comment]
- [ ] Initialize everything to clockwise
- [ ] Support pencil strokes (open)
- [ ] Support shape strokes (closed)
- [ ] Fix bug where two shapes with same color cause intersection issues 
- [ ] other bugs if they exist in testing files (Quadrome, My Project7-16-2020_2-13-55PM)
- [ ] Fill same object more than twice (only sometimes breaks)
- [ ] Catch looping case, call onError

**Comment by Luxapodular** [comment]
Wonderful job by @nick-wick on the new fill bucket! Testing is available on test.wickeditor.com!
