### ISSUE TITLE
Outliner Tool

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#205]
**Is your feature request related to a problem? Please describe.**
On complex canvases, it is difficult to manipulate objects on the screen. Additionally, users are unable to table through objects on the canvas and timeline, making accessible manipuplations impossible.

**Describe the solution you'd like**
A docked panel int he interface that outlines all frames, layers, and objects currently visible.

**Describe alternatives you've considered**
Needs research.

**Comment by nick-wick** [comment]
Here is an interactive demo of an outliner made in wick:
[OutlinerDemo5-20-2020_4-21-41PM.zip](https://github.com/Wicklets/wick-editor/files/4662986/OutlinerDemo5-20-2020_4-21-41PM.zip)

And some sketches of potential placements of the outliner in the overall UI:
![IMG_2867](https://user-images.githubusercontent.com/65551186/82569896-b75b3000-9b35-11ea-84da-ef18cb9b62cd.JPG)
![IMG_2868](https://user-images.githubusercontent.com/65551186/82569911-baeeb700-9b35-11ea-8482-aa56e027adaf.JPG)

**Comment by nick-wick** [comment]
Forum post with user feedback: https://forum.wickeditor.com/t/requesting-feedback-on-a-new-feature/2721

Potential designs (desktop version with a popout menu, iPad version with tabs):
![OutlinerConcept_desktop_popout](https://user-images.githubusercontent.com/65551186/82689012-afbb8a00-9c0e-11ea-9bf3-ac00189cee61.jpg)
![OutlinerConcept_iPad_tabs](https://user-images.githubusercontent.com/65551186/82689029-b3e7a780-9c0e-11ea-894e-db56489f2c76.jpg)

**Comment by nick-wick** [comment]
Here's a document with desired functionality of the outliner:
https://docs.google.com/document/d/1eOVH-V7CYZFz_qkgZ7YHsY3LnbJQyHG1jD846EslQ1k/edit?usp=sharing

Here are some images of what it might look like to select items, move them between or into other items, and to have an "acitve" item (for the purpose of navigating the outliner with keyboard only):
Selecting:
![selection](https://user-images.githubusercontent.com/65551186/82927997-62a12600-9f36-11ea-8fd5-0a4806499a81.png)
Moving between:
![moving1](https://user-images.githubusercontent.com/65551186/82928003-659c1680-9f36-11ea-92b6-c0354acd6030.png)
Moving into:
![moving2](https://user-images.githubusercontent.com/65551186/82928008-67fe7080-9f36-11ea-93d4-2af25f3b301f.png)
Active
![active](https://user-images.githubusercontent.com/65551186/82928016-6af96100-9f36-11ea-853e-e17b7b3eff20.png)

**Comment by nick-wick** [comment]
Latest version includes multi-selection! Still need to add visibility/locked buttons for layers, moving items, sound indicator, potentially alternating background color of objects depending on depth in tree, and write shouldComponentUpdate (currently runs quickly up to about 5000 list items, but this is on a powerful machine).
![outliner_demo1](https://user-images.githubusercontent.com/65551186/83458481-7e656a00-a417-11ea-9c16-04f732314fad.gif)
