### ISSUE TITLE
Images in clones don't render [BUG]

### ISSUE THREAD

**Issue by nick-wick** [Wicklets/wick-editor#208]
**Describe the bug**
When a clip with an image is cloned, the image doesn't render. From the forum: https://forum.wickeditor.com/t/cloning-image-problem/2726/2

**To Reproduce**
Make a clip with an image in it, add a script to clone it.
When playing the project, the images on the clone won't render.

![image_clone_bug](https://user-images.githubusercontent.com/65551186/82914624-97a47d00-9f24-11ea-921b-e32c39a47254.gif)

**Expected behavior**
Images in clones should render.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Wick 1.17.1

**Comment by jovannyrodz** [comment]
Yup, Jovanny here, from the forum... This is the one that I noticed last night... (Wick 1.18 - test)
