### ISSUE TITLE
[BUG] (minor) Single Frame mode still shows "synced" checkbox

### ISSUE THREAD

**Issue by kryptot7** [Wicklets/wick-editor#211]
**Describe the bug**
Single Frame mode for Clips still shows the "synced" checkbox even though it's not needed (since the Clip will no longer play at all). Trying to activate the checkbox does nothing.

**To Reproduce**
1. Create a Clip
2. Set playback mode to Single Frame
3. Click on "sync" checkbox

**Expected behavior**
No checkbox needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/30781325/83581785-c6ff4f00-a50d-11ea-89b9-a8101238f930.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: MS Edge Chromium
 - Version 83

**Comment by Luxapodular** [comment]
Fixed in 1.18!
