### ISSUE TITLE
[BUG] Add Labels to Inputs throughout editor

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#214]
**Describe the bug**
Many text labels for inputs use divs or spans, should use <label> elements with name="" properties.

name="" of input should be name="" of label.

- [x] Inspector
- [x] Toolbox
- [x] Filter for asset
- [x] Editor Settings Modal
- [x] Export Modal

**Comment by nick-wick** [comment]
Commit defb1eb2 in nick-wick outliner branch: Dual Labels in Inspector now have each property
