### ISSUE TITLE
[BUG] Zooming changes effective brush size

### ISSUE THREAD

**Issue by ComradeSparklePony** [Wicklets/wick-editor#285]
**Describe the bug**
Drawing with the brush produces different stroke widths depending on zoom level, when the brush size is the same. I'm assuming this is a bug as this doesn't happen with the pencil.

**To Reproduce**
1. Open up the editor [https://editor.wickeditor.com/(https://editor.wickeditor.com/)
2. Select the brush tool
3. Draw anything
4. Press the "Zoom In" or "Zoom Out" button
5. Draw anything

**Expected behavior**
I expect the brush size to be consistent regardless of zoom level. When I zoom in, the stroke of the brush should be larger to compensate so that lines drawn while zoomed in and zoomed out with the brush tool are the same width.

**Screenshots**
![Screen Shot 2020-10-22 at 4 49 28 PM](https://user-images.githubusercontent.com/27787087/96928688-f431a700-1486-11eb-93c2-005c5848bdb1.png)
Both lines in the above screenshot were drawn with the same brush width, but at different zoom levels.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 1.18

**Additional context**
Not relevant to the issue, but just wanted to thank you for your work with Wick!

**Comment by ComradeSparklePony** [comment]
Just tried it in version 1.19 at test.wickeditor.com, the problem applies there as well.

**Comment by Luxapodular** [comment]
Hi @ComradeSparklePony, thanks for the report. We actually have two brush settings "Relative" and "non-relative". You can select this using the "Relative brush size" option in the tool bar! 

<img width="283" alt="Screen Shot 2020-10-26 at 12 08 15 PM" src="https://user-images.githubusercontent.com/8699557/97197361-f5631c80-1783-11eb-86da-4cbb9b4652ad.png">

I'm going to close this for now, but please comment if this does not solve your issue.

**Comment by ComradeSparklePony** [comment]
Yep, that solved it! Thank you!
