### ISSUE TITLE
[BUG] Code Editor is blurry macOS Safari

### ISSUE THREAD

**Issue by sporklpony** [Wicklets/wick-editor#295]
**Describe the bug**
In macOS Safari, the script editor (everything in the modal, not just the code) appears blurry compared to the rest of the interface. It works as expected (not blurry) in Firefox. This issue appears to happen both in 1.18 and 1.19. Other modals do not appear to have this issue.
![Screen Shot 2020-12-02 at 6 59 07 AM](https://user-images.githubusercontent.com/27787087/100870287-5f01d500-346c-11eb-9ffd-5114e914527f.png)

**To Reproduce**
1. Visit editor.wickeditor.com or test.wickeditor.com in Safari on macOS.
2. Edit the default script of the first frame.
3. Observe blurriness.

**Expected behavior**
The Code Editor should appear cleanly like everything else, without blurriness.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Safari 14.0.1
 - Version: 1.18, 1.19

**Comment by Luxapodular** [comment]
Hey @sporklpony would you mind checking this out on test.wickeditor.com? The code editor there has a new design which might fix the issue!

**Comment by sporklpony** [comment]
Unfortunately it appears to still be happening on test.wickeditor.com.
![Screen Shot 2020-12-02 at 10 57 42 AM](https://user-images.githubusercontent.com/27787087/100897021-4229c980-348d-11eb-84ab-ce7bc5882027.png)

**Comment by sporklpony** [comment]
I just tested again, and it appears to be fixed! Closing issue.
