### ISSUE TITLE
[BUG] Code Editor Reference button text overflows in Firefox

### ISSUE THREAD

**Issue by sporklpony** [Wicklets/wick-editor#296]
**Describe the bug**
For Wick 1.19, In Firefox, the text for some of the buttons (Timeline and Random) in the Reference overflows the edge of the button.
![Screen Shot 2020-12-02 at 7 14 06 AM](https://user-images.githubusercontent.com/27787087/100871534-70e47780-346e-11eb-900f-0a78b5190a95.png)

**To Reproduce**
1. Visit test.wickeditor.com in Firefox.
2. Open the script editor.

**Expected behavior**
The button should encapsulate all of the text within.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Firefox 83.0
 - Version: 1.19

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**
One solution might just be to make the sidebar and buttons wider by default.

**Comment by Luxapodular** [comment]
Hey @sporklpony , I don't have this issue in firefox or chrome. I added some changes in the recent branch that **should** fix this but check it out and let me know if it persists.

**Comment by sporklpony** [comment]
I just tried again with the latest 1.19 branch and it still appears to be happening... weird.
![Screen Shot 2020-12-03 at 3 47 45 PM](https://user-images.githubusercontent.com/27787087/101086739-4afac800-357f-11eb-810e-abca5825d923.png)

I'm not sure if this is useful, but the text doesn't overflow when I click to the sub-menu.
![Screen Shot 2020-12-03 at 3 51 40 PM](https://user-images.githubusercontent.com/27787087/101086896-7f6e8400-357f-11eb-9159-e94795e61d49.png)

Quick mildly related question: I've mostly been using the master branch when doing development... should I be using 1.19 instead?

Thank you!

**Comment by sporklpony** [comment]
I just tried again on test.wickeditor.com as well as the 1.19 branch served locally and it appears to be resolved! Don't know why it wasn't working earlier, maybe a caching issue. But I think we're all set!
