### ISSUE TITLE
[BUG] Editor crashed after drawing several lines in same layer

### ISSUE THREAD

**Issue by claudioznsantos** [Wicklets/wick-editor#323]
Greetings, first of all, the editor is amazing, thanks for creating it. 
I'm using the editor to create sprites for my game.  
The bug happens after I draw about 40 lines, or brush lines, on the same layer.  
The screen goes blank, freezes, and I am forced to shut down the application and start it again.

1. Make some basic lines in 2 or 3 layers
2. Lock all layers
3. Create a new layer and begin to draw lines(In my case was a stutter for a window)
4. After that, in all my attempts the editor crashed

My system is:
 - OS: POP_OS!  20.10
I'm using the downloadable version:
 - Version [1.19]

It's just a wild guess, but I believe it must be something related to memory management, during that part of the execution.

Guys, really sorry to bother you with that, but that seems very important. Also, if I could make a suggestion, I would say to create a function to merge lines together, that would be very interesting. 
And as I said earlier, it is great, I'll keep betting on wick editor, and I hope soon I will be to donating to the project.

**Comment by mayhair** [comment]
Why did you close this?

**Comment by claudioznsantos** [comment]
After searching through the web and seeing that no one posted anything about it but me, I thought it was me misusing the software somehow, didn't want to bother the others and decided closed it.
