### ISSUE TITLE
[BUG] Do not issue bug reports!

### ISSUE THREAD

**Issue by ghost** [Wicklets/wick-editor#380]
Wick Editor is no longer maintained! Any bug requests will never be read.
If you'd like to fix these bugs yourself, fork Wick and share the source code with us.

**Comment by Zaydiscool777** [comment]
seems to be updated just today… are you sure?

**Comment by ghost** [comment]
> seems to be updated just today… are you sure?

What updates? Are you seeing something that I'm not? Is it on this very repo?!

**Comment by Zaydiscool777** [comment]
I can't be exactly sure, but I have noticed two things: One, being that the outline is expandable, rather than being part of the side bar, and that two, on desktop, the stroke and fill color icons are circles rather than Cs.

**Comment by Zaydiscool777** [comment]
purple 🙃
