### ISSUE TITLE
[BUG] Assets are not draggable from the asset library on mobile or touch displays.

### ISSUE THREAD

**Issue by Luxapodular** [Wicklets/wick-editor#45]
**Describe the bug**
When adding assets on touchscreen devices, they cannot be dragged from the asset library to the canvas.

**To Reproduce**
1. Add an asset on a touch screen device.
2. Attempt to drag the asset to the canvas.
3. See error

**Expected behavior**
Assets should be draggable and add automatically to the canvas from all devices.

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**

We may need to change a setting on react-dnd, the library we use for dragging assets, or switch libraries entirely.

**Comment by Luxapodular** [comment]
This will require integration of TouchBackend from React DND or some equivalent backend to complete. The HTML5 backend we are using does not have touch support.

**Comment by zrispo** [comment]
Possible solution:
Create an "add asset to canvas" button which adds an instance of the asset to the center of the canvas.

(see this thread on the forum: https://forum.wickeditor.com/t/drag-and-drop-asset-is-there-an-other-way-to-add-them/2356/11)

**Comment by Luxapodular** [comment]
Image Assets now have an "Add to canvas" button in the inspector which should allow touch users to use them now.
