### ISSUE TITLE
[BUG] If the currently picked color is transparent, the drawing tools feel like they are broken

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#53]
**Describe the bug**
Trying to draw with a transparent color makes it look like the drawing tools are not working at all. This happens very often when drawing shapes with no fills, then later switching to the brush, forgetting that the fill color is set to `rgba(0,0,0,0)`.

**Expected behavior**
Make sure the drawing tools are never "broken" (currently there is no feedback when the mouse is dragged)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chome
 - Version 79.0.3945.88

**Do you have a suggested solution to this issue? (ex. has another program fixed this bug a certain way? Are you familiar with where in the code base someone would need to fix this issue?)**
One solution is to automatically change the active color to a solid color when a drawing tool is selected (only if the color is on transparent).

**Comment by sporklpony** [comment]
Another approach might be to softly outline what is drawn, like when dragging a path around the screen.

**Comment by Luxapodular** [comment]
Fixed in 1.19 in commit ae0984
