### ISSUE TITLE
[BUG] Zoom box does not accurately zoom

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#59]
**Describe the bug**
The zoom tool can draw rectangles that, when the mouse is released, set the project's zoom and pan such that the canvas fits neatly inside the rectangle. The math for this was never implemented fully, so the zoom box feature currently uses a naive pan and zoom based on the center and width of the rectangle, making the zoom box feel inaccurate at times.

**Expected behavior**
Original canvas:
![Screen Shot 2020-01-06 at 1 47 11 PM](https://user-images.githubusercontent.com/4970417/71840330-20f90700-308b-11ea-8357-fb17181208eb.png)

Canvas, after drawing a rectangle with the zoom tool around the circle:
![Screen Shot 2020-01-06 at 1 47 06 PM](https://user-images.githubusercontent.com/4970417/71840332-222a3400-308b-11ea-952b-fba4fcf6d064.png)

The top and bottom of the circle should be touching the edges of the screen.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 79.0.3945.88

**Comment by ComradeSparklePony** [comment]
This should be fixed with #291. Sorry for all the notifications here, I was having issues with git.
