### ISSUE TITLE
[BUG] Huion tablets on windows can't click lock/hide buttons on timeline

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#62]
**Describe the bug**
Using a Huion tablet on a Windows machine makes it impossible to click the buttons on layers in the timeline GUI.

May be related to #42.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 79.0.3945.88

**Comment by kryptot7** [comment]
I can confirm this issue. I'm running into in on Windows 10 x64, MS Edge Chromium. I'm using a Turcom TS6580 with Huion drivers. (That brand of tablets is compatible with Huion drivers.)

**Comment by Luxapodular** [comment]
This issue seems to extend to most touch screens as well.

**Comment by Luxapodular** [comment]
TouchStart is firing mousedown a second time.
