### ISSUE TITLE
Brush modes: Paint behind, paint selection, etc.

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#79]
**Is your feature request related to a problem? Please describe.**
Adobe Flash/Animate has a cool feature where the brush can be set to respond differently depending on what's on the canvas. See the included link for more info about this feature.

**Additional context**
http://www.informit.com/articles/article.aspx?p=1312651&seqNum=25

**Comment by kryptot7** [comment]
It'd also be helpful if...
- These modes were available to the eraser as well
- When in Paint or Erase Selected mode but there's no selection, the brush behaves as normal. That way you can leave it on and when you need to paint/erase inside something, just select it first
