### ISSUE TITLE
[BUG] Selecting many objects is extremely slow

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#86]
**Describe the bug**
Marking this as a bug as something is definitely wrong with the selection code - after about fifty or so objects, selection becomes almost unusable due to lag. 

This may be an issue where some routine related to selection is  being performed once for each object selected instead of being performed once at the end of the whole selection process.

**Comment by Luxapodular** [comment]
Made a few updates to selection. Now has a selectMultipleObjects and deselectMultipleObjects which runs around 50x faster!
