### ISSUE TITLE
Downloadable desktop editor

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#87]
**Is your feature request related to a problem? Please describe.**
One of the most requested features for the editor is a downloadable version.

**Additional context**
Currently, there are Windows and MacOS builds that are functional (see the main readme in this repo on how to build). 

The most major thing missing here is for the executables to be signed, which is something that must be done for security reasons (and because Windows and MacOS get grumpy when programs are unsigned - it doesn't look good).

Another feature that still needs to be built is an automatic update system. There are a few pretty good options for this, however most of them require an update server which means spending some money on server costs.

**Comment by Luxapodular** [comment]
Make sure to build this in: https://desktop.github.com/terms/

**Comment by Luxapodular** [comment]
Using Github Desktop as a reference, additional things we'll need include:

**A way to turn off usage statistics:**
![github_information](https://user-images.githubusercontent.com/8699557/73367520-a97b5980-427d-11ea-9489-c172e1c9d947.png)

**Full TOS and Open Source Licenses:**
![image](https://user-images.githubusercontent.com/8699557/73367598-be57ed00-427d-11ea-83f4-dcf06625cd1d.png)

**A way to update the software:**
![image](https://user-images.githubusercontent.com/8699557/73367647-ce6fcc80-427d-11ea-808f-43ca8ce5b9c1.png)

**Possible considerations of an auto updater:**

**An Easy way to report bugs and contact:**
![image](https://user-images.githubusercontent.com/8699557/73367693-e2b3c980-427d-11ea-9f7b-6a2fa9fa21a4.png)

**A Logo usage page:**
https://github.com/logos

**Comment by Luxapodular** [comment]
For Installers:
- TOS Screen
- Signed Applications

**Comment by AndreaMonzini** [comment]
Hello i am testing `Wick.Editor-1.18.0.AppImage` on GNU/Linux.
Are statistic or other privacy related info sent from the Appimage?
Thank you.
