### ISSUE TITLE
[BUG] Dropdowns in inspector get covered up by asset library on low resolutions

### ISSUE THREAD

**Issue by zrispo** [Wicklets/wick-editor#92]
**Describe the bug**
Instead of displaying over other elements on the page, dropdown menus are somehow being covered up by other elements.

**Screenshots**
![Screen Shot 2020-01-07 at 11 42 03 AM](https://user-images.githubusercontent.com/4970417/71912078-dd61d400-3142-11ea-9131-07dbcccc1af7.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 79.0.3945.88

**Comment by Luxapodular** [comment]
May need to revert to normal HTML select dropdowns... React-select seems to not allow this behavior.

**Comment by sporklpony** [comment]
I think this should be resolved with PR #300
